# -*- coding: utf-8 -*-
"""FuncionesDeActivacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JJmw8o96W2_vJnwbj3A_2Mj0BBMPoyOZ
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

# Valores de entrada
x = torch.tensor([-1.0, 1.0, 2.0, 3.0])

# Uso de softmax
output = torch.softmax(x, dim=0)
print(output)

sm = nn.Softmax(dim=0)
output = sm(x)
print(output)

# Uso de sigmoid
output = torch.sigmoid(x)
print(output)

s = nn.Sigmoid()
output = s(x)
print(output)

# Uso de tanh
output = torch.tanh(x)
print(output)

t = nn.Tanh()
output = t(x)
print(output)

# Uso de ReLU
output = torch.relu(x)
print(output)

relu = nn.ReLU()
output = relu(x)
print(output)

# Uso de Leaky ReLU
output = F.leaky_relu(x)
print(output)

lrelu = nn.LeakyReLU()
output = lrelu(x)
print(output)

# Creación de un modelo de red neuronal con módulos nn
class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(NeuralNet, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(hidden_size, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

# Uso de funciones de activación directamente en la evaluación
class NeuralNet2(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(NeuralNet2, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.linear2 = nn.Linear(hidden_size, 1)

    def forward(self, x):
        out = torch.relu(self.linear1(x))
        out = torch.sigmoid(self.linear2(out))
        return out