# -*- coding: utf-8 -*-
"""SoftmaxyCrossentropy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N2PZe2v4Y_nrrzV1Zqt0D2N7QPS7D-kd
"""

import torch
import torch.nn as nn
import numpy as np

# Definición de softmax en numpy
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

# Ejemplo de vector en R3
x = np.array([2.0, 1.0, 0.1])
outputs = softmax(x)
print("Softmax numpy:", outputs)

# Definición de softmax en PyTorch
x = torch.tensor([2.0, 1.0, 0.1])
outputs = torch.softmax(x, dim=0)
print("Softmax torch:", outputs)

# Definición de cross entropy en numpy
def cross_entropy(actual, predicted):
    EPS = 1e-15
    predicted = np.clip(predicted, EPS, 1 - EPS)
    loss = -np.sum(actual * np.log(predicted))
    return loss

# Ejemplo de cross entropy en numpy
Y = np.array([0, 1, 0])
Y_pred_good = np.array([0.7, 0.2, 0.1])
Y_pred_bad = np.array([0.1, 0.3, 0.6])
l1 = cross_entropy(Y, Y_pred_good)
l2 = cross_entropy(Y, Y_pred_bad)
print(f"Loss1 numpy: {l1:.4f}")
print(f"Loss2 numpy: {l2:.4f}")

# Cross entropy en PyTorch
loss = nn.CrossEntropyLoss()

# Ejemplo de cross entropy en PyTorch
Y = torch.tensor([2], dtype=torch.long)
Y_pred_good = torch.tensor([[0.05, 0.1, 0.85]])
Y_pred_bad = torch.tensor([[0.3, 0.3, 0.4]])
l1 = loss(Y_pred_good, Y)
l2 = loss(Y_pred_bad, Y)
print(f"PyTorch Loss1: {l1.item():.4f}")
print(f"PyTorch Loss2: {l2.item():.4f}")

# Predicciones (regresa el índice del máximo valor)
_, predictions1 = torch.max(Y_pred_good, 1)
_, predictions2 = torch.max(Y_pred_bad, 1)
print(f"Actual class: {Y.item()}, Y_pred1: {predictions1.item()}, Y_pred2: {predictions2.item()}")

# Clasificación binaria (red neuronal)
class NeuralNet1(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(NeuralNet1, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(hidden_size, 1)

    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        y_pred = torch.sigmoid(out)
        return y_pred

# Clasificación para múltiples clases
class NeuralNet2(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(NeuralNet2, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        return out